// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RANUISWANSONFOOTBALLCLUB_WEBSITE.Migrations
{
    [DbContext(typeof(RANUISWANSONFOOTBALLCLUB_DATABASE))]
    partial class RANUISWANSONFOOTBALLCLUB_DATABASEModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Coaches", b =>
                {
                    b.Property<int>("Coaches_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Coaches_ID"));

                    b.Property<string>("Coach_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coach_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coach_Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coach_Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayersPlayer_ID")
                        .HasColumnType("int");

                    b.HasKey("Coaches_ID");

                    b.HasIndex("PlayersPlayer_ID");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Managers", b =>
                {
                    b.Property<int>("Manager_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manager_ID"));

                    b.Property<string>("Manager_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manger_Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamsTeam_ID")
                        .HasColumnType("int");

                    b.HasKey("Manager_ID");

                    b.HasIndex("TeamsTeam_ID");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Players", b =>
                {
                    b.Property<int>("Player_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Player_ID"));

                    b.Property<string>("Player_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player_Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player_Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionsTransaction_ID")
                        .HasColumnType("int");

                    b.HasKey("Player_ID");

                    b.HasIndex("TransactionsTransaction_ID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Positions", b =>
                {
                    b.Property<int>("Positions_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Positions_ID"));

                    b.Property<int?>("PlayersPlayer_ID")
                        .HasColumnType("int");

                    b.Property<int>("Position_Name")
                        .HasColumnType("int");

                    b.HasKey("Positions_ID");

                    b.HasIndex("PlayersPlayer_ID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Teams", b =>
                {
                    b.Property<int>("Team_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Team_ID"));

                    b.Property<int?>("PlayersPlayer_ID")
                        .HasColumnType("int");

                    b.Property<string>("Team_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Team_ID");

                    b.HasIndex("PlayersPlayer_ID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Transactions", b =>
                {
                    b.Property<int>("Transaction_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transaction_ID"));

                    b.Property<decimal>("Transaction_Fee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Transaction_ID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Coaches", b =>
                {
                    b.HasOne("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Players", null)
                        .WithMany("Coaches")
                        .HasForeignKey("PlayersPlayer_ID");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Managers", b =>
                {
                    b.HasOne("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Teams", null)
                        .WithMany("Managers")
                        .HasForeignKey("TeamsTeam_ID");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Players", b =>
                {
                    b.HasOne("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Transactions", null)
                        .WithMany("Players")
                        .HasForeignKey("TransactionsTransaction_ID");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Positions", b =>
                {
                    b.HasOne("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Players", null)
                        .WithMany("Positions")
                        .HasForeignKey("PlayersPlayer_ID");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Teams", b =>
                {
                    b.HasOne("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Players", null)
                        .WithMany("Teams")
                        .HasForeignKey("PlayersPlayer_ID");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Players", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Positions");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Teams", b =>
                {
                    b.Navigation("Managers");
                });

            modelBuilder.Entity("RANUISWANSONFOOTBALLCLUB_WEBSITE.Models.Transactions", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
